### ISSUE TITLE
插件市场更新0.1.4 LiteLoader无法使用

### ISSUE THREAD

**Issue by shi-an** [LiteLoaderQQNT/LiteLoaderQQNT-Plugins-Marketplace#19]
插件市场更新0.1.4  LiteLoader就寄了

**Comment by MUKAPP** [comment]
我也

**Comment by MUKAPP** [comment]
日志里没发现问题，但是qq内未成功加载llqqnt
![image](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/assets/41848070/3cc6ea54-a9bc-4745-9b8b-5ed7c6999221)
![image](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/assets/41848070/3624a150-6656-43e9-9d0f-a35ec1d5cdf7)

**Comment by mo-jinran** [comment]
请尝试删除config.json解决

**Comment by systemoutprintlnhelloworld** [comment]
> 请尝试删除config.json解决
Windows 11系统下9.9.2.16736版本 删除config也没能出现插件市场
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugins-Marketplace/assets/62531937/d7d2e14e-39f5-41b6-917d-467d6c036ed4)

**Comment by shi-an** [comment]
9.9.2.16736 LiteLoaderQQNT能用了？

> > 请尝试删除config.json解决
> > Windows 11系统下9.9.2.16736版本 删除config也没能出现插件市场
> > ![image](https://user-images.githubusercontent.com/62531937/269629298-d7d2e14e-39f5-41b6-917d-467d6c036ed4.png)

**Comment by systemoutprintlnhelloworld** [comment]
> 9.9.2.16736 LiteLoaderQQNT能用了？
> 
> > > 请尝试删除config.json解决
> > > Windows 11系统下9.9.2.16736版本 删除config也没能出现插件市场
> > > ![image](https://user-images.githubusercontent.com/62531937/269629298-d7d2e14e-39f5-41b6-917d-467d6c036ed4.png)

并不能,我是没有其他版本的安装包而已
